# Site settings
title: Taylor Wu's Blog
email: taylorwu21@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is Taylor Wu's personal website. Created to document the progress of my programming
  and new technology I have learned about.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://taylorwu21.github.io/" # the base hostname & protocol for your site
twitter_username: https://twitter.com/DrinkMySoySauce
github_username:  taylorwu21

# Build settings
markdown: kramdown
